import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import {
  DeleteObjectCommand,
  GetObjectCommand,
  NoSuchKey,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3';
import type { Config } from '../config.js';

/** Where uploaded files live. Keys are generated by the server, never by users. */
export interface FileStorage {
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<{ data: Buffer; contentType: string } | null>;
  delete(key: string): Promise<void>;
}

const SAFE_KEY = /^[a-z0-9][a-z0-9/_.-]{0,200}$/;

function assertSafeKey(key: string): void {
  // Keys are server-made, but a bad key could escape the storage folder, so check anyway.
  if (!SAFE_KEY.test(key) || key.includes('..')) throw new Error(`Unsafe storage key "${key}"`);
}

/** Files on local disk: development, tests, or a mounted volume. */
export class LocalFileStorage implements FileStorage {
  constructor(private readonly root: string) {}

  private file(key: string) {
    assertSafeKey(key);
    return path.join(this.root, ...key.split('/'));
  }

  async put(key: string, data: Buffer, contentType: string): Promise<void> {
    const f = this.file(key);
    await mkdir(path.dirname(f), { recursive: true });
    await writeFile(f, data);
    await writeFile(`${f}.type`, contentType);
  }

  async get(key: string) {
    const f = this.file(key);
    try {
      const [data, contentType] = await Promise.all([readFile(f), readFile(`${f}.type`, 'utf8')]);
      return { data, contentType };
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    const f = this.file(key);
    await rm(f, { force: true });
    await rm(`${f}.type`, { force: true });
  }
}

/** Any S3-compatible store (AWS S3, Cloudflare R2, MinIO…). */
export class S3FileStorage implements FileStorage {
  private readonly client: S3Client;

  constructor(
    private readonly bucket: string,
    options: { region: string; endpoint?: string; accessKeyId?: string; secretAccessKey?: string },
  ) {
    this.client = new S3Client({
      region: options.region,
      ...(options.endpoint ? { endpoint: options.endpoint, forcePathStyle: true } : {}),
      ...(options.accessKeyId && options.secretAccessKey
        ? {
            credentials: {
              accessKeyId: options.accessKeyId,
              secretAccessKey: options.secretAccessKey,
            },
          }
        : {}),
    });
  }

  async put(key: string, data: Buffer, contentType: string): Promise<void> {
    assertSafeKey(key);
    await this.client.send(
      new PutObjectCommand({ Bucket: this.bucket, Key: key, Body: data, ContentType: contentType }),
    );
  }

  async get(key: string) {
    assertSafeKey(key);
    try {
      const res = await this.client.send(new GetObjectCommand({ Bucket: this.bucket, Key: key }));
      if (!res.Body) return null;
      const data = Buffer.from(await res.Body.transformToByteArray());
      return { data, contentType: res.ContentType ?? 'application/octet-stream' };
    } catch (err) {
      if (err instanceof NoSuchKey) return null;
      throw err;
    }
  }

  async delete(key: string): Promise<void> {
    assertSafeKey(key);
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }
}

export function createStorage(config: Config): FileStorage {
  if (config.STORAGE_DRIVER === 's3') {
    if (!config.S3_BUCKET || !config.S3_REGION) throw new Error('S3 storage is not configured');
    return new S3FileStorage(config.S3_BUCKET, {
      region: config.S3_REGION,
      ...(config.S3_ENDPOINT ? { endpoint: config.S3_ENDPOINT } : {}),
      ...(config.S3_ACCESS_KEY_ID ? { accessKeyId: config.S3_ACCESS_KEY_ID } : {}),
      ...(config.S3_SECRET_ACCESS_KEY ? { secretAccessKey: config.S3_SECRET_ACCESS_KEY } : {}),
    });
  }
  return new LocalFileStorage(path.resolve(config.STORAGE_LOCAL_DIR));
}
